### ISSUE TITLE
Roadmap To Wavy 0.10.0

### ISSUE THREAD

**Issue by AldaronLau** [libcala/wavy#34]
- [ ] Update to pasts 0.12.x https://github.com/libcala/wavy/pull/45
 - [x] Release fon 0.6.0
 - [ ] Use upgraded fon 0.6.0
 - [ ] Upgrade lookit crate to pasts 0.12.x
 - [ ] Use lookit crate for quick asynchronous device discovery on Linux
 - [ ] Figure out async discovery in JavaScript
 - [ ] Make all types `Send` with whisk and smelling_salts 0.7.x https://github.com/libcala/wavy/issues/30

See https://github.com/libcala/wavy/issues/46 for next version roadmap.

**Comment by beckend** [comment]
Ability to select hardware by name? `Microphone::Default()` is very limiting.

**Comment by AldaronLau** [comment]
@beckend you can already select hardware by name, more or less like this:

```rust
let mics = Microphone::query();

let (i, _mic_name) = mics
    .iter()
    .map(|m| format!("{m}"))
    .enumerate()
    .filter(|(_i, n)| n == "Microphone Name")
    .next()
    .expect("Microphone doesn't exist");

let mic = mics[i];
```
