### ISSUE TITLE
Roadmap To Wavy 0.11.0

### ISSUE THREAD

**Issue by AldaronLau** [libcala/wavy#46]
- [ ] Finally finish groundwork for MacOS Support
 - [ ] Windows support?
 - [ ] Support microphones that don't work in interleaved f32le, (fallback to i24le, then i16le) - Convert to f32
 - [ ] Support AudioWorklet as alternate DOM API (Maybe Push to 0.11.0)
